# 高效多维数组

## 随机数生成

In [2]:
import numpy as np

data = np.random.randn(2,3)
data
data.shape

(2, 3)

## 生成数组

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
np.arange(15) #range的数组版

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
a = np.ones((3,6))

In [7]:
np.zeros_like(a)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
np.full((3,6),10)

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 数组运算
消灭for循环

In [10]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr *arr
arr.dot(arr.T)

array([[14, 32],
       [32, 77]])

## 数组切片
对切片运算相当于对原数组

## 布尔索引
~符号表取反

## 神奇索引

In [12]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [13]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [14]:
arr[[0,1,2],[1,2,3]]

array([0., 1., 2.])

## 数组转置和换轴

In [15]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [17]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [18]:
arr.swapaxes(1,2) #第三维和第二维度交换

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## 通用函数：快速的逐个元素数组函数

## sqrt、exp、add、maximum
modf:返回所有数组元素的浮点数的小数部分和整数部分
abs:绝对值
square:平方
log\log10\log2\log1p
sign:计算每个元素的符号值
ceil:向上取整
floor：向下取整，rint
二元：
subtract:在第二个数组中去除第一个数组包含的元素
power:第二各数组元素作为第一个数组元素的幂次方
mod:求模（余数）
copysign:第一个数组的符号改成第二个数组的符号


In [19]:
arr1 = np.random.rand(3,4)
arr2 = np.full((3,4),2)
np.power(arr1, arr2)

array([[0.34151788, 0.52149651, 0.68137209, 0.28018678],
       [0.00603408, 0.52958245, 0.05724288, 0.89546316],
       [0.58013985, 0.1100707 , 0.2513993 , 0.65737877]])

# 面向数组的编程

np.where(条件，真时值，假时值)

In [20]:
arr = np.random.randn(5,4)

In [21]:
arr.mean(1) #等价于axis=1

array([-0.07828323, -0.57053711,  0.31546212, -0.90344651, -0.43375225])

cumsum(axis=0)按列累计求和
cumprod(axis=1)按行累计求积

排序 np.sort()

# 线性代数

In [22]:
from numpy.linalg import inv, qr

In [23]:
import matplotlib.pyplot as plt
n = 10000
p = 2000
draws = np.random.randint(0, 2, size=(n,p))

s = np.where(draws>0, 1, -1)
w = s.cumsum(1)
w
# plt.plot(w)
# plt.show()

array([[  1,   0,  -1, ...,  38,  39,  40],
       [  1,   2,   3, ..., -12, -13, -12],
       [ -1,  -2,  -3, ...,  42,  41,  42],
       ...,
       [ -1,  -2,  -1, ...,  16,  17,  18],
       [ -1,   0,  -1, ...,  52,  51,  52],
       [ -1,   0,  -1, ...,  54,  55,  54]], dtype=int32)

In [24]:
w.max()

188

In [27]:
hist30 = (np.abs(w)>=30).any(1)
hist30

array([ True,  True,  True, ...,  True,  True,  True])